### ISSUE TITLE
Code Inconsistency

### ISSUE THREAD

**Issue by Sub-Xaero** [EphyraSoftware/Acropolis#30]
### Connection Repository
`ConnectionRepository#getByFromIdAndFromType()` - Confusing name, Should probably just be `getFromIdAndFromType` or `getByIDAndType`

### Project Service
Service has names like:
```
    fun createProject(name: String)
    fun deleteProject(id: Long)
    fun listProjects(): List<ProjectEntity>
    fun getProject(name: String): ProjectEntity
```

Where other services are just 
```
    fun create(name: String)
    fun delete(id: Long)
    fun list(): List<ProjectEntity>
    fun get(name: String): ProjectEntity
```

**Comment by ThetaSinner** [comment]
Any types on the repository interfaces are for generated code, so the naming is important. Don't know if it can figure out what to generate if you change the method names.

I know the services have inconsistent names. I haven't even been consistent myself. We've got enough now that we can probably pick a naming setup. If you rename lots of things and get it all tidy could you start a markdown page somewhere in the repo to document code style - specifically around naming methods on services etc :)
