### ISSUE TITLE
Service layer project getters

### ISSUE THREAD

**Issue by Sub-Xaero** [EphyraSoftware/Acropolis#42]
`ApplicationSoftwareService#create`, and most other services' `#create` methods, take a Project ID and assign it to a new ProjectEntity.
```kotlin
override fun create(projectId: Long, name: String) {
        val project = ProjectEntity()
        project.id = projectId
```
which I assume is just a lazy way of getting the ID into the database without having to check for project existence.

`NetworkService#create` takes a project name and fetches it from the database. 
```kotlin
    override fun create(name: String, projectName: String) {
        val project = projectService.get(projectName)

        if (project == null) {
            Logger.error("Could not find project with name [$projectName]")
            throw IllegalStateException("Project not found [$projectName]")
        } 
```
this should probably be done unilaterally

**Comment by ThetaSinner** [comment]
Either way is valid. The one that takes an id and sets it on a new DatabaseEntity is essentially setting up a join by taking advantage of hibernate.

This is something we were talking about the other day. The services should use one of the other and really names would be nicer, but one isn't really better than the other and it would be great to have both. So if all of them are converted to use names then I'll take a look at creating some sort of interception which can be used as an interface to the services to use the ids instead
