### ISSUE TITLE
Networks, Software and Compute Instances

### ISSUE THREAD

**Issue by Sub-Xaero** [EphyraSoftware/Acropolis#46]
@EphyraSoftware/ephyra-dev May or may not be an issue, but just so that we have a public record of the discussion.

Continuing my work on `ComputeInstances`, I'm debating how it slots in with `Networks`

So the way we've implemented `Networks`, `ApplicationSoftware` and `SystemSoftware` can be associated with a `GroupingEntity` which is then associated with a `NetworkEntity`. 

# 1
Do we want to allow this continue, and allow the `ComputeInstance` parent relationship to be optional, and add `ComputeInstance` as just another Grouping under `GroupingEntity`? 
Thereby, if Software exists on the Network without a host, just presume the user doesn't care what it runs on, and only render specifics when a host is present? 

```
Network 
  -> Grouping
     -> Datastore
     -> *Application Software
     -> *System Software
     -> Compute Instance
          -> Application Software
          -> System Software
```

because in most instances, particularly for smaller use cases, the answer for "what does it run on?" might just be "Idk, a server?"

# 2
Or, 
should `ComputeInstance` simply be the receptacle for all `ApplicationSoftware` and `SystemSoftware`, and replace all references to software in a `GroupingEntity` with `ComputeInstances` which contain software? 

```
Network 
  -> Grouping
     -> Datastore
     -> Compute Instance
          -> Application Software
          -> System Software
```

**Comment by ThetaSinner** [comment]
From conversation suggestion is

- Move datastore to system software
- attach compute instance to network directly rather than using grouping
- move grouping entity to top level (project) and give it a name field + create a service for it
